site_name: Daniel Szortyka
site_url: https://dszortyka.github.io
use_directory_urls: true
strict: false

# Repository Info
repo_name: dszortyka.github.io
repo_url: https://github.com/dszortyka/dszortyka.github.io
edit_uri: edit/master/docs


#theme.analytics.gtag: 

# Theme Config
theme:
  name: material
  analytics:
    gtag: 'G-PY3KTHSJCE'

markdown_extensions:
  - attr_list

nav:
  - Home: 'index.md'
  - 'Tech Blog': 
    - 'Kubernetes - Redis monitoring with Prometheus and Grafana': 'Tech Blog/k8s-prometheus-grafana-redis-monitoring.md'
    - 'How to setup a Basic DNS Server with Debian and Bind': 'Tech Blog/basic-dns-setup-on-debian.md'
    - 'How to setup GitHub Pages': 'Tech Blog/getting-started-github-pages.md'
    - 'Python Unit Tests Compilation': 'Tech Blog/python-unit-tests-compilation.md'
#    - 'Vulnerability Management of your Application projects': 'Tech Blog/getting-started-with-dependency-track-and-software-bill-of-materials.md'


extra:
  analytics:
    provider: google
    property: G-PY3KTHSJCE
